/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  owner?: string | null;
}
export type ExecuteMsg = {
  create_collection: CollectionParams;
} | {
  mint_n_f_t: MintParams;
};
export interface CollectionParams {
  code_id: number;
  name: string;
  symbol: string;
}
export interface MintParams {
  code_id: number;
  owner: string;
  token_id: string;
  token_uri: string;
}
export type QueryMsg = {
  query_config: {};
};
export type Addr = string;
export interface ConfigResponse {
  collection_address: Addr;
  config: Config;
}
export interface Config {
  owner: Addr;
}